taks/esp32-nimble

src/client/ble_advertised_device.rs

Here is my implementation to #6
Feel free to rewrite and improve it.
Im still a beginner in rust, so expect mistakes and let me know them.

Manufacture Data

---

src/server/ble_characteristic.rs

I added a callback that is called when a characteristic is subscribed and a function that exposes the number of current subscribers. `NimbleSub` is set to `pub` because it is used in the callback signature.

Add BLECharacteristic::on_subscribe event and subscribed_count

---

src/ble_security.rs
src/enums.rs

Add resolve_rpa function

---

src/ble_device.rs
src/client/ble_client.rs
src/client/ble_scan.rs
src/enums.rs
src/server/ble_advertising.rs
src/server/ble_ext_advertising.rs

Added functions to set own address.

---

src/ble_device.rs

Fix #37 link error
reference: https://github.com/espressif/esp-idf/issues/11893#issuecomment-1639549702

Fix link error for esp32c3

---

src/client/ble_advertised_device.rs

Changed to accept invalid ut8 string.

---

Cargo.toml

Use once_cell/std

---

src/server/ble_advertising.rs

Added BLEAdvertising::min_interval, BLEAdvertising::max_interval

---

src/client/ble_client.rs

Added BLEClient::get_rssi

---

examples/ble_server.rs

Fixed crash when max connections reached

---

src/server/ble_advertising.rs

Mark BLEAdvertising as Send

---

examples/ble_secure_server.rs

Added code for multi connections to the ble_secure_sever example

---

.github/workflows/ci.yml
src/server/ble_advertising.rs

Fix advertising

---

src/server/ble_advertising.rs

Fixed advertising length calculation

---

src/client/ble_client.rs
src/server/ble_server.rs

Added disconnect and disconnect_with_reason

---

examples/ble_start_stop.rs
src/ble_device.rs
src/client/ble_scan.rs
src/server/ble_server.rs

Added BLEDevice::deinit_full

---

README.md
src/ble_security.rs
src/lib.rs
src/server/ble_server.rs

Update README.md with Passkey details

---

src/server/ble_advertising.rs

convert BLE_ERR_INV_HCI_CMD_PARMS to BLE_HS_EINVAL

---

CHANGELOG.md

Fix URLs in changelog.

---

src/server/ble_characteristic.rs
src/server/ble_server.rs
src/server/ble_service.rs
src/utilities/mutex.rs

Added Accessor Functions

---

examples/ble_keyboard.rs

fixes https://github.com/taks/esp32-nimble/issues/119

Add resolve_rpa to keyboard example

---

src/client/ble_client.rs

Guru Meditation Error occurs if a disconnect event occurs after the BLEClient has been dropped.

Fix Guru Meditation Error

---

src/ble_address.rs

BleAddress LE and BE functions (breaking change)

---

examples/ble_client.rs
examples/ble_l2cap_client.rs
examples/ble_secure_client.rs
src/ble_device.rs
src/client/ble_client.rs

Enforce BLEClient creation via BLEDevice instance.

---

build.rs
src/server/ble_characteristic.rs

Fix ESP-IDF v5.2.2 build

---

src/server/ble_characteristic.rs

Changed on_read closure argument from `AttValue` to `Self`

---

src/client/ble_remote_characteristic.rs

Fix `on_notify` when data is long

---

build.rs
src/server/ble_characteristic.rs

Adding the version to the check seems to compile fine! :)

Fix ESP-IDF v5.4 build

---

examples/ble_secure_server.rs
src/server/ble_server.rs

Added `&mut Self` argument to on_authentication_complete callback

---

src/client/ble_client.rs
src/client/ble_remote_characteristic.rs
src/client/ble_remote_service.rs

Fix null pointer dereferences

---

src/ble_error.rs
src/lib.rs

Remove inline_const_pat
