src/client/mod.rs
Make the BLEServiceData struct public, so that advertised data can be accessed by an application.
=> Make BLEServiceData public

src/client/ble_client.rs
I added `on_connect` and `on_disconnect` callbacks to `BLEClient`.
I'm not quite sure if the call in `BLE_GAP_EVENT_CONNECT` is correct or if the callback should be called analogous to the client state signal, which in case of a successful mtu exchange would be after that if I'm reading that correctly?
Tested with a successful connection to an Android device.
=> Add on_connect and on_disconnect callbacks to BLEClient

Cargo.toml, src/utilities/mutex.rs
Updated cargo esp-rs crates dependencies.
I found that when generating a new project using https://github.com/esp-rs/esp-idf-template template, I was unable to build the project because new versions of the esp-rs crates were already in use. This PR fixes this.
=> Update esp-rs crates dependencies

src/utilities/ble_uuid.rs
Implement the  `From<uuid::Uuid>` trait for BleUuid to allow usage of those uuids by calling into().
In my case i have a common lib used by a client and the esp32. The client library uses the uuid lib for it's ble service/characteristic ids. By implementing this i can now use a common uuid:Uuid value and pass it to nimble functions by calling into()
=> allow to convert uuid::Uuid value to BleUuid

src/server/ble_advertising.rs
For unknown reasons v0.2.1 changed the default advertising start duration to 0 which causes it to effectively disable advertising immediately.  The documentation suggests we should use BLE_HS_FOREVER which according to host/ble_hs.h is INT32_MAX, though that constant isn't made available through esp_idf_sys for some reason.
Closes #28, #29
=> Fix advertising regression in v0.2.1

.github/workflows/ci.yml, Cargo.toml
Added esp32-nimble into an esp32 std project and failed to build.
That's because critical-section used a built-in critical section implementation when std enabled.
So I think it's better to add a feature in this project to make it work with std.
=> Add feature for building with std support

src/enums.rs, src/server/ble_advertising.rs
=> Add `disc_mode` and `high_duty_cycle` functions.

examples/ble_client.rs, src/client/ble_remote_characteristic.rs
Aligned the API with h2zero/NimBLE-Arduino, namely: [NimBLE-Arduino RemoteCharacteristic](https://github.com/h2zero/NimBLE-Arduino/blob/bc333ccb6e8d9ff2059af9cbd5006a290a4de3a5/src/NimBLERemoteCharacteristic.cpp#L106).
=> Add notification check and properties to BLE characteristic

examples/ble_client.rs, examples/ble_secure_client.rs, src/client/ble_scan.rs
This PR simplifies the BLE device scanning process.
**Before:**
```rust
let connect_device = Arc::new(Mutex::new(None));
let device0 = connect_device.clone();
scan.on_result(move |scan, device| {
if device.name().contains("ESP32") {
scan.stop().unwrap();
(*device0.lock()) = Some(device.clone());
}
});
scan.start(10000).await.unwrap();
let device = &*connect_device.lock();
if let Some(device) = device {
info!("Advertised Device: {:?}", device);
}
```
**After:**
```rust
scan.on_result(|device| {
if device.name().contains("Shelly") {
Some(device)
} else {
None
}
});
if let Some(device) = scan.start(10000).await.unwrap() {
info!("Advertised Device: {:?}", device);
}
```
The device returned by `on_result` is the return value for `start`. I removed the `scan` argument to `on_result`, but I'm …
=> Streamlined BLE Device Scanning Process

examples/ble_client.rs, src/client/ble_remote_characteristic.rs, src/client/ble_remote_service.rs
This allows for easier debugging when working with clients. Debug (`{:?}`) now includes the most valuable fields, and display (`{}`) consists of the `uuid`, and, in the case of the characteristic, `properties`.
Here's an example:
```
I (4039) ble_client: (display) BLERemoteService[0x1812]
I (4039) ble_client: (debug) BLERemoteService { uuid: 0x1812, start_handle: 24, end_handle: 47, characteristics: Some([0x2a4e, 0x2a4d, 0x2a4d, 0x2a4d, 0x2a4b, 0x2a22, 0x2a32, 0x2a4a, 0x2a4c]) }
I (4059) NimBLE: GATT procedure initiated: discover all characteristics;
I (4069) NimBLE: start_handle=48 end_handle=65535
I (4829) ble_client: (display) BLERemoteCharacteristic[f3641401-00b0-4240-ba50-05ca45bf8abc]
I (4829) ble_client: (debug) BLERemoteCharacteristic { uuid: f3641401-00b0-4240-ba50-05ca45bf8abc, …
```
=> Implement Display and Debug traits for BLERemoteCharacteristic & BLERemoteService

src/server/ble_characteristic.rs, src/server/ble_descriptor.rs, src/server/mod.rs, src/server/on_write_args.rs
=> Added OnWriteDescriptorArgs, OnWriteArgs::notify

README.md
The configuration options mentioned in the README work reliably for iOS devices. Unfortunately, I don't have any sources to back up my statements, but it works for all my iOS 16 & 17 devices against ESP32 and ESP32C3.
=> Configuring for iOS Auto-Reconnect

.cargo/config.toml
This is needed for `cargo run` to flash the program on my ESP32-C3.
=> Update espflash command for riscv32

src/server/ble_characteristic.rs
This caused a lot of confusion for me because I was calling `.lock()` inside the `on_write` callback.
=> Add warning about the characteristic being locked during `on_write`

examples/ble_server.rs, examples/ble_start_stop.rs, src/server/ble_characteristic.rs, src/server/ble_descriptor.rs, src/server/on_write_args.rs
=> Added current_data to OnWriteArgs

src/client/ble_writer.rs
This fixes a panic if `write_value()` is called on a closed connection. See #90.
Not sure if `BLE_HS_ENOTCONN` is the best error code to use for such a situation, though.
=> Avoid int underflow in BLEWriter::write_value()

src/ble_return_code.rs
I added in the remaining codes from [https://mynewt.apache.org/latest/network/ble_hs/ble_hs_return_codes.html](https://mynewt.apache.org/latest/network/ble_hs/ble_hs_return_codes.html)
I'm not sure what to do with `esp_idf_sys::BLE_HS_ERR_HW_BASE` I looked around and didn't find any definitions.
=> Fixes Add missing return codes for security manager #93

src/ble_address.rs
**Description:**
This pull request implements the `PartialEq` and `Eq` traits for the `BLEAddress` and `BLEAddressType` types . These traits are essential for enabling equality comparison between instances of these types, improving the usability and robustness of the library.
**Changes Made:**
- Implemented `PartialEq` and `Eq` traits for `BLEAddress`.
- Implemented `PartialEq` and `Eq` traits for `BLEAddressType`.
- Adjusted the comparison logic to ensure correctness and consistency.
**Reason for Changes:**
By implementing these traits, users of the esp32-nimble library can easily compare `BLEAddress`  instances, leading to more intuitive and reliable code.
=> Implement PartialEq and Eq for BLEAddress and BLEAddressType

src/ble_address.rs
This pull request modifies the PartialEq implementation for the `BLEAddress` struct. Previously, it compared both the value and the type of the BLE address. However, after careful consideration, it was determined that comparing the type of address is not crucial and might add unnecessary complexity for users. Therefore, this pull request simplifies the comparison by only considering the value of the address.
- Modified the `eq` method in the `PartialEq` implementation for `BLEAddress` to only compare the address values.
- Removed the comparison of address types in the `eq` method.
By focusing solely on comparing the address values, this change simplifies the interface for users of the `BLEAddress` struct. Users no longer need to be concerned about the specific type of the address, leading …
=> The PartialEq implementation for the BLEAddress struct modified

src/client/ble_remote_characteristic.rs
If the characteristic is not the last one in a service `next_char_cb` will be called again with the next characteristic which in the current implementation would override the end handle and would again send the state signal.
The double state signal then leads to `get_descriptors` returning an empty array, can be tested with this sample code:
```rust
let characteristic = service
.get_characteristic(characteristic_uuid)
.await
.unwrap();
let uuids: Vec<_> = characteristic
.get_descriptors()
.await
.unwrap()
.map(|d| d.uuid().to_string())
.collect();
log::info!("subscribe to {:?}", uuids);
```
I haven't found any documentation about what the callback is supposed to return but I found out that returning HS_DONE would not call the callback again. Also Nimble-Arduino also does this so it seems …
=> Return BLE_HS_EDONE in characteristic discovery

src/server/ble_characteristic.rs
Add some docs to make it more obvious that `BLECharacteristic::on_subscription` also includes un-subscription events. I had assumed that a on_unsub method just wasn't implemented until I poked around more. The inability to make a zero-flags variant in bitflags also led to the confusion so added some docs there.
=> Add docs to BLECharacteristic::on_subscription

.github/workflows/ci.yml, src/server/ble_characteristic.rs, src/server/ble_service.rs
=> Added BLECharacteristic.cpfd

src/client/ble_advertised_device.rs, src/client/ble_scan.rs
This pull request fixes an issue in the `esp32-nimble` where the `rssi` field of the `BLEAdvertisedDevice` structure was not updated during the discovery process when an advertising report was received.
During the BLE discovery process, the Received Signal Strength Indicator (RSSI) value in the `BLEAdvertisedDevice` structure was not being updated properly. This resulted in incorrect or missing RSSI data for discovered devices.
The solution involves updating the RSSI field of the `BLEAdvertisedDevice` structure upon receiving an advertising report. The necessary changes have been made to ensure that the RSSI value is correctly captured and updated.
Please let me know if there are any additional changes required . I appreciate your review and feedback.
Thank you!
=> # Fix: Update RSSI Field in BLEAdvertisedDevice Structure During Discovery

src/server/ble_characteristic.rs
This was a stumbling block for me so I added what I could get from other sources. But I have yet to find a definitive Authentication vs Authorization definition (specific to BLE), so I feel like that needs more clarification. It might be useful to add a 'requires key exchange' or something similar.
Might add a usage doc to the struct for those unfamiliar with bitflags.
This is just to start a conversation.
Open to suggestions/corrections.
=> Add member docs to NimbleProperties

src/client/ble_attribute.rs, src/client/ble_client.rs, src/client/ble_remote_characteristic.rs, src/client/ble_remote_service.rs
=> Fixed BLEClient dropping multiple times

build.rs, src/server/ble_characteristic.rs, src/server/ble_service.rs, src/server/mod.rs
The `cfg(all(...))` gating for the cpfd module, added in #114, is not working for ESP-IDF versions > 5.2.
This patch introduces a new cfg, `cpfd`, that is set from the build script if ESP-IDF version is above 5.2.1. The new cfg is then used to conditionally include the cpfd support.
=> Fix cpfd config attribute

.github/workflows/ci.yml, src/server/ble_characteristic.rs, src/utilities/mutex.rs
=> Fix deadlock in BLECharacteristic::handle_gap_event

Cargo.toml
Breaking: Update esp-idf-svc and embassy-time to latest version.
=> chore: bump esp-idf-svc and embassy-time version

src/server/ble_characteristic.rs
The handle_gap_event that lead to deadlocks where an invalid connection handle 65535 would occur after a failed notify ( no clue what caused that to occur). 
The connection handle value was 65535(highest value for u16) which is an invalid conn_handle (unless someone somehow managed to connect that many devices).
The `try_lock() `worked as a stop gap but it would lead to failed read/write attempts when notify was in progress which would lead to disconnection.
=> Added connection Handle check before gap event is handled in characteristic to fix the deadlock issue in #151
